// meta design house http status and error message enum
const enums = {
   Continue : {CODE: 100, CONSTANT: 'HTTP_STATUS_CONTINUE', MESSAGE: '요청을 계속할 수 있습니다.'},
   SwitchingProtocols : {CODE: 101, CONSTANT: 'HTTP_STATUS_SWITCH_PROTOCOLS', MESSAGE: '서버가 업그레이드 헤더에서 프로토콜을 전환했습니다.'},
   Ok : {CODE: 200, CONSTANT: 'HTTP_STATUS_OK', MESSAGE: '요청이 성공적으로 완료되었습니다.'},
   Created : {CODE: 201, CONSTANT: 'HTTP_STATUS_CREATED', MESSAGE: '요청이 처리되어 새 리소스가 생성되었습니다.'},
   Accepted : {CODE: 202, CONSTANT: 'HTTP_STATUS_ACCEPTED', MESSAGE: '처리를 위해 요청이 수락되었지만 처리가 완료되지 않았습니다.'},
   Partial : {CODE: 203, CONSTANT: 'HTTP_STATUS_PARTIAL', MESSAGE: '엔터티 헤더에서 반환된 메타 정보는 원래 서버에서 사용할 수 있는 최종 집합이 아닙니다.'},
   NoContent : {CODE: 204, CONSTANT: 'HTTP_STATUS_NO_CONTENT', MESSAGE: '서버가 요청을 처리했지만 다시 보낼 새 정보는 없습니다.'},
   ResetContent : {CODE: 205, CONSTANT: 'HTTP_STATUS_RESET_CONTENT', MESSAGE: '요청이 완료되었으며 클라이언트 프로그램은 사용자가 다른 입력 작업을 쉽게 시작할 수 있도록 요청을 전송한 문서 보기를 다시 설정해야 합니다.'},
   PartialContent : {CODE: 206, CONSTANT: 'HTTP_STATUS_PARTIAL_CONTENT', MESSAGE: '서버가 리소스에 대한 부분 GET 요청을 처리했습니다.'},
   WebdavMultiStatus : {CODE: 207, CONSTANT: 'HTTP_STATUS_WEBDAV_MULTI_STATUS', MESSAGE: 'WebDAV(World Wide Web Distributed Authoring and Versioning) 작업 중에 단일 응답에 대한 여러 상태 코드를 나타냅니다. 응답 본문에는 상태 코드를 설명하는 XML(Extensible Markup Language)이 포함되어 있습니다. '},
   Ambiguous : {CODE: 300, CONSTANT: 'HTTP_STATUS_AMBIGUOUS', MESSAGE: '요청된 리소스는 하나 이상의 위치에서 사용할 수 있습니다.'},
   Moved : {CODE: 301, CONSTANT: 'HTTP_STATUS_MOVED', MESSAGE: '요청된 리소스가 새 영구 URI(Uniform Resource Identifier)에 할당되었으며, 이 리소스에 대한 향후 참조는 반환된 URI 중 하나를 사용하여 수행해야 합니다.'},
   Redirect : {CODE: 302, CONSTANT: 'HTTP_STATUS_REDIRECT', MESSAGE: '요청된 리소스는 다른 URI 아래에 일시적으로 상주합니다.'},
   RedirectMethod : {CODE: 303, CONSTANT: 'HTTP_STATUS_REDIRECT_METHOD', MESSAGE: '요청에 대한 응답은 다른 URI에서 찾을 수 있으며 해당 리소스의 GET HTTP 동사를 사용하여 검색해야 합니다.'},
   NotModified : {CODE: 304, CONSTANT: 'HTTP_STATUS_NOT_MODIFIED', MESSAGE: '요청된 리소스가 수정되지 않았습니다.'},
   UseProxy : {CODE: 305, CONSTANT: 'HTTP_STATUS_USE_PROXY', MESSAGE: '요청된 리소스는 위치 필드에서 제공하는 프록시를 통해 액세스해야 합니다.'},
   RedirectKeepVerb : {CODE: 307, CONSTANT: 'HTTP_STATUS_REDIRECT_KEEP_VERB', MESSAGE: '리디렉션된 요청은 동일한 HTTP 동사를 유지합니다.'},
   BadRequest : {CODE: 400, CONSTANT: 'HTTP_STATUS_BAD_REQUEST', MESSAGE: '잘못된 구문으로 인해 서버에서 요청을 처리할 수 없습니다.'},
   Denied : {CODE: 401, CONSTANT: 'HTTP_STATUS_DENIED', MESSAGE: '요청한 리소스를 사용하려면 사용자 인증이 필요합니다.'},
   PaymentReq : {CODE: 402, CONSTANT: 'HTTP_STATUS_PAYMENT_REQ', MESSAGE: 'HTTP 프로토콜에서 구현되지 않습니다.'},
   Forbidden : {CODE: 403, CONSTANT: 'HTTP_STATUS_FORBIDDEN', MESSAGE: '서버는 요청을 이해했지만 처리할 수 없습니다.'},
   NotFound : {CODE: 404, CONSTANT: 'HTTP_STATUS_NOT_FOUND', MESSAGE: '서버에서 요청된 URI와 일치하는 항목을 찾지 못했습니다.'},
   BadMethod : {CODE: 405, CONSTANT: 'HTTP_STATUS_BAD_METHOD', MESSAGE: '사용된 HTTP 동사는 허용되지 않습니다.'},
   NoneAcceptable : {CODE: 406, CONSTANT: 'HTTP_STATUS_NONE_ACCEPTABLE', MESSAGE: '클라이언트에 허용되는 응답을 찾을 수 없습니다.'},
   ProxyAuthReq : {CODE: 407, CONSTANT: 'HTTP_STATUS_PROXY_AUTH_REQ', MESSAGE: '프록시 인증이 필요합니다.'},
   RequestTimeout : {CODE: 408, CONSTANT: 'HTTP_STATUS_REQUEST_TIMEOUT', MESSAGE: '서버가 요청을 기다리는 동안 시간이 초과되었습니다.'},
   Conflict : {CODE: 409, CONSTANT: 'HTTP_STATUS_CONFLICT', MESSAGE: '리소스의 현재 상태와 충돌하여 요청을 완료할 수 없습니다. 사용자는 추가 정보를 다시 제출해야 합니다.'},
   Gone : {CODE: 410, CONSTANT: 'HTTP_STATUS_GONE', MESSAGE: '요청된 리소스는 서버에서 더 이상 사용할 수 없으며 전달 주소를 알 수 없습니다.'},
   LengthRequired : {CODE: 411, CONSTANT: 'HTTP_STATUS_LENGTH_REQUIRED', MESSAGE: '서버는 정의된 콘텐츠 길이 없이 요청을 수락할 수 없습니다.'},
   PrecondFailed : {CODE: 412, CONSTANT: 'HTTP_STATUS_PRECOND_FAILED', MESSAGE: '서버에서 테스트할 때 false로 평가된 하나 이상의 요청 헤더 필드에 지정된 전제 조건입니다.'},
   RequestTooLarge : {CODE: 413, CONSTANT: 'HTTP_STATUS_REQUEST_TOO_LARGE', MESSAGE: '요청 엔터티가 서버에서 처리할 수 있는 것보다 크기 때문에 서버에서 요청을 처리할 수 없습니다.'},
   UriTooLong : {CODE: 414, CONSTANT: 'HTTP_STATUS_URI_TOO_LONG', MESSAGE: '요청 URI가 서버에서 해석할 수 있는 것보다 길기 때문에 서버에서 요청을 서비스할 수 없습니다.'},
   UnsupportedMedia : {CODE: 415, CONSTANT: 'HTTP_STATUS_UNSUPPORTED_MEDIA', MESSAGE: '요청의 엔터티가 요청된 메서드에 대해 요청된 리소스에서 지원되지 않는 형식이므로 서버에서 요청을 서비스할 수 없습니다.'},
   RetryWith : {CODE: 449, CONSTANT: 'HTTP_STATUS_RETRY_WITH', MESSAGE: '적절한 작업을 수행한 후 요청을 다시 시도해야 합니다.'},
   ServerError : {CODE: 500, CONSTANT: 'HTTP_STATUS_SERVER_ERROR', MESSAGE: '서버에서 요청을 이행하지 못하는 예기치 않은 조건이 발생했습니다.'},
   NotSupported : {CODE: 501, CONSTANT: 'HTTP_STATUS_NOT_SUPPORTED', MESSAGE: '서버는 요청을 수행하는 데 필요한 기능을 지원하지 않습니다.'},
   BadGateway : {CODE: 502, CONSTANT: 'HTTP_STATUS_BAD_GATEWAY', MESSAGE: '서버는 게이트웨이 또는 프록시 역할을 하는 동안 요청을 수행하기 위해 액세스한 업스트림 서버로부터 잘못된 응답을 받았습니다.'},
   ServiceUnavail : {CODE: 503, CONSTANT: 'HTTP_STATUS_SERVICE_UNAVAIL', MESSAGE: '서비스가 일시적으로 오버로드됩니다.'},
   GatewayTimeout : {CODE: 504, CONSTANT: 'HTTP_STATUS_GATEWAY_TIMEOUT', MESSAGE: '게이트웨이를 대기하는 동안 요청의 시간이 초과되었습니다.'},
   VersionNotSup : {CODE: 505, CONSTANT: 'HTTP_STATUS_VERSION_NOT_SUP', MESSAGE: '서버는 요청 메시지에 사용된 HTTP 프로토콜 버전을 지원하지 않습니다.'}
};

module.exports = { enums };